production: &production
  action_mailer_host: "<%=ENV['ABF_HOST'] %>"
  tmpfs_path: /tmp
  root_path: /share
  git_path: /home/mnt/gitstore
  do-not-reply-email: do-not-reply@rosalinux.ru
  project_name: ABF
  github_services:
    ip: 10.76.0.242
    port: 4000
  distr_types: ['mdv', 'rhel', 'arm', 'dnf']
  allowed_addresses:
    - 127.0.0.1
    - ::1
  abf_worker:
    publish_workers_count: 4
  keys:
    key_pair_secret_key: "<%=ENV['KEY_PAIR_SECRET_KEY'] %>"
    secret_token: "<%=ENV['SECRET_TOKEN'] %>"
    secret_key_base: "<%=ENV['SECRET_KEY_BASE'] %>"
    devise:
      pepper: "<%=ENV['DEVISE_PEPPER'] %>"
      secret: "<%=ENV['DEVISE_SECRET'] %>"

  anonymous_access: true
  mailer_https_url: true
  file_store_url: <%=ENV['FILE_STORE_URL'] %>
  wiki_formats:
    markdown:  "Markdown"
    textile:   "Textile"
    org:       "Org-mode"
  shell_user: 'git'
  downloads_url: "<%=ENV['DOWNLOADS_URL'] %>"

development:
  <<: *production
