clean_rpm_build_nodes:
  every:
    - '1m'
  class: 'CleanRpmBuildNodeJob'
  queue: middle
  description: 'Cleans RPM build nodes'

build_lists_publish_task_manager:
  every:
    - '3m'
  class: 'PublishTaskManagerJob'
  queue: middle
  description: 'Creates tasks for publishing'

clean_api_defender_statistics:
  every:
    - '1d'
  class: 'CleanApiDefenderStatisticsJob'
  queue: low
  description: 'Cleans ApiDefender statistics'

clean_build_list_buildroot:
  every:
    - '1h'
  class: 'BuildLists::CleanBuildrootJob'
  queue: middle
  description: 'Cleans RPM buildroot from BuildList'

run_extra_mass_builds:
  every:
    - '5m'
  class: 'RunExtraMassBuildsJob'
  queue: low
  description: 'Run mass builds with relations'

remove_outdated_items:
  cron: '0 3 * * *'
  class: 'RemoveOutdatedItemsJob'
  queue: low
  description: 'Removes outdated mass builds, product build lists and build lists'

autostart_builds_daily:
  cron: '0 4 * * *'
  class: 'AutostartBuildsDailyJob'
  queue: low
  description: 'Starts automatic builds every 24 hours'

autostart_regens_daily:
  cron: '0 4 * * *'
  class: 'AutostartRegensDailyJob'
  queue: low
  description: 'Starts automatic metadata regenerations every 24 hours'

autostart_builds_once_every_twelve_hours:
  cron: '0 4,16 * * *'
  class: 'AutostartBuildsOnceEveryTwelveHoursJob'
  queue: low
  description: 'Starts automatic builds every 12 hours'

autostart_builds_weekly:
  cron: '0 4 * * 0'
  class: 'AutostartBuildsWeeklyJob'
  queue: low
  description: 'Starts automatic builds every week'

autostart_regens_weekly:
  cron: '0 4 * * 0'
  class: 'AutostartRegensWeeklyJob'
  queue: low
  description: 'Starts automatic builds every week'

clean_temp_pull_requests:
  cront: '30 3 * * *'
  class: 'CleanTempPullRequestsJob'
  queue: low
  description: Clean temporary pull request files more that a day old

build_canceling_destroy:
  every:
    - '10m'
  class: 'BuildLists::BuildCancelingDestroyJob'
  queue: low
  description: 'Remove build canceling build lists'

clear_stale_builders:
  every:
    - '5m'
  class: 'ClearStaleBuildersJob'
  queue: low
  description: 'Clear jobs with builders who did not send build started'

clear_unused_invites:
  every:
    - '5m'
  class: 'ClearUnusedInvitesJob'
  queue: low
  description: 'Clear unused invites that have surpassed their ttl'
